### ISSUE TITLE
Error: Cannot find module 'ansi-escapes' after updating Ionic CLI (local version) to 3.10.3 => 3.12.0

### ISSUE THREAD

**Issue by JeetChaudhari** [ionic-team/ionic-cli#2760]
**Description:**
Error: Cannot find module 'ansi-escapes' after updating Ionic CLI (local version) to 3.10.3 => 3.12.0

There was message in console while doing `ionic serve` as follows
```
? The Ionic CLI (local version) has an update available (3.10.3 => 3.12.0)! Would you like to install it? Yes
> npm install --save-dev --save-exact ionic@latest
√ Running command - done!

[OK] Updated Ionic CLI to 3.12.0! 🎉

Please re-run your command.

Note: You can downgrade to your old version by running: npm install --save --save-exact ionic@3.10.3
```
After re - running command it generated following error.

**Output:**
```
{ Error: Cannot find module 'ansi-escapes'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (PROJECT_PATH\node_modules\inquirer\lib\utils\readline.js:2:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
```

**My `ionic info`:**

`ionic info` also does not work and gives same above mentioned error

**Comment by dwieeb** [comment]
Try these steps:

```
npm uninstall ionic
npm uninstall -g ionic
npm install -g ionic
```

**Comment by JeetChaudhari** [comment]
@dwieeb It worked, after doing steps mentioned by you the error disappeared and it started and working again, thank you.
