### ISSUE TITLE
v3.8.0 and later contains heavy breaking changes

### ISSUE THREAD

**Issue by timbru31** [ionic-team/ionic-cli#2663]
**Steps to Reproduce:**

0. Have an Angular project, where just the Ionic cloud features are used
1. Upgrade to ionic-cli v3.8.0 or later
2. Run in a CI environment or install ionic **not** globally.

First of all, gulp integration is now enabled - per default. We don't want this. Although this can be disabled, it's enabled for the first run. Besides that, it crashes:

```shell
> ionic "upload" "--deploy" "playground" "--note" "git: a23f3023223e5412b60ea6282867f6e0696e414d"

[ANNOUNCE] Hi! Welcome to CLI 3.9.

           We decided to merge core plugins back into the main ionic CLI package. The @ionic/cli-plugin-ionic-angular, @ionic/cli-plugin-ionic1, @ionic/cli-plugin-cordova, and @ionic/cli-plugin-gulp plugins have all been deprecated and won't be loaded by the CLI anymore. We listened to devs and determined they added unnecessary complexity. You can uninstall them from your project(s).
           
           No functionality was removed and all commands will continue working normally. You may wish to review the CHANGELOG: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#changelog
           
           Thanks,
           The Ionic Team
           
           
[INFO] Enabling Gulp integration.
> ionic config set integrations.gulp {} --json --force
[OK] integrations.gulp set to {} in ./ionic.config.json!
Error: Cannot find module '/builds/.../our-app/node_modules/@ionic/app-scripts'
```

After disabling gulp integration, it crashes, since the app-scripts are not automatically installed:

```shell
❯ CI=true npm run ionic -- upload --deploy playground --note "git: $CI_COMMIT_SHA"                                                                                                                                               [17:42:19]

> our-app@0.16.0 ionic /Users/timbru/work/../our-app
> ionic "upload" "--deploy" "playground" "--note" "git: "

Error: Cannot find module '/Users/timbru/work/.../our-app/node_modules/@ionic/app-scripts'

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/timbru/.nvm/versions/node/v6.11.2/bin/node" "/Users/timbru/.nvm/versions/node/v6.11.2/bin/npm" "run" "ionic" "--" "upload" "--deploy" "playground" "--note" "git: "
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! our-project@0.16.0 ionic: `ionic "upload" "--deploy" "playground" "--note" "git: "`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the our-project@0.16.0 ionic script 'ionic "upload" "--deploy" "playground" "--note" "git: "'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the our-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic "upload" "--deploy" "playground" "--note" "git: "
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs our-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls our-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/timbru/work/.../our-app/npm-debug.log
```

After installing app-scripts via `npm i --save-dev @ionic/app-scripts` (the package was not necessary before, so more burden to install), it does not find the entry point anymore. Why does it look at all for it? **Prior we just built the app ourselves via `ng` and uploaded the `www` folder!**

```shell
❯ CI=true npm run ionic -- upload --deploy playground --note "git: $CI_COMMIT_SHA"                                                                                                                                               [17:47:02]

> our-app@0.16.0 ionic /Users/timbru/work/.../our-app
> ionic "upload" "--deploy" "playground" "--note" "git: "

Running app-scripts build:

[17:47:08]  build dev started ...
Error: /Users/timbru/work/.../our-app/src/app/main.ts was not found. The "main.dev.ts" and "main.prod.ts" files have been deprecated. Please create a new file "main.ts" containing the content of "main.dev.ts", and then delete the deprecated files.
                            For more information, please see the default Ionic project main.ts file here:
                            https://github.com/ionic-team/ionic2-app-base/tree/master/src/app/main.ts
```

Brings me to fix the error via the `package.json` config section - why can't I set this in `ionic.config.json`?

And now, it does not even transpile anymore:

```shell
❯ CI=true npm run ionic -- upload --deploy playground --note "git: $CI_COMMIT_SHA"                                                                                                                                               [17:49:53]

> our-app@0.16.0 ionic /Users/timbru/work/.../our-app
> ionic "upload" "--deploy" "playground" "--note" "git: "

Running app-scripts build:

[17:49:58]  build dev started ...
[17:49:58]  clean started ...
[17:49:58]  clean finished in less than 1 ms
[17:49:58]  copy started ...
[17:49:58]  transpile started ...
[17:50:05]  template error, "/Users/timbru/work/.../our-app/dist/out-tsc/src/app/app.component.html": Error:
            ENOENT: no such file or directory, open
            '/Users/timbru/work/.../our-app/dist/out-tsc/src/app/app.component.html'
[...]

[17:50:05]  transpile finished in 7.09 s
[17:50:05]  preprocess started ...
[17:50:05]  deeplinks started ...
Error: Could not find IonicModule.forRoot call in "imports"
```

**My `ionic info`:**
```shell
❯ npm run ionic info                                                                                                                                                                                                             [17:39:38]

> our-app@0.16.0 ionic /Users/timbru/work/../our-app
> ionic "info"

[ERROR] Error with ./node_modules/ionic-angular/package.json file: FILE_NOT_FOUND
[ERROR] Error with ./node_modules/@ionic/app-scripts/package.json file: FILE_NOT_FOUND

cli packages: (/Users/timbru/work/.../our-app/node_modules)

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

local packages:

    @ionic/app-scripts : not installed
    Ionic Framework    : not installed

System:

    Node : v6.11.2
    npm  : 3.10.10
    OS   : macOS Sierra
```


**Other Information:**
n/a

**Comment by timbru31** [comment]
Basically we want to disable all integrations that we now are forced to use, I guess

**Comment by timbru31** [comment]
Fun fact: setting `type` in `ionic.config.json` to something else than `ionic-angular` or `ionic1` the whole integrations thing is disabled 🎉

**Comment by dwieeb** [comment]
Gulp was enabled because it was detected in your `package.json`. Most people using gulp are using Ionic 1, and it hooks into [CLI hooks](https://github.com/ionic-team/ionic-cli#cli-hooks). `@ionic/app-scripts` is installed by default for Ionic Angular projects. 

What kind of project is this? Where is `ionic-angular`? 

We invoke a build during `ionic upload` so that the generated files are up-to-date with the app source. You can disable this with `--nobuild`.

**Comment by timbru31** [comment]
> Gulp was enabled because it was detected in your package.json. Most people using gulp are using Ionic 1, and it hooks into CLI hooks. @ionic/app-scripts is installed by default for Ionic Angular projects.

Yeah, I've read that. Gulp is going to be removed soon from our project, so an integration is not needed for us.

> What kind of project is this? Where is ionic-angular?

We don't have ionic-angular (yet) installed, since so far we are only interested in the cloud services (Auth, Deploy and later Push)

> We invoke a build during ionic upload so that the generated files are up-to-date with the app source. You can disable this with --nobuild.

Thanks, `--nobuild` does the trick. Maybe state the flag in the README?

**Comment by dwieeb** [comment]
Ah, okay, I understand. This isn't an Ionic (framework) project. I'm curious how it detected an Ionic Angular project to begin with.

**Comment by timbru31** [comment]
Because the whole project relies that a type is defined in the `ionic.config.json` file: https://github.com/ionic-team/ionic-cli/blob/1d0f21c3bad7b1214c8e7bd35a34adb492478c51/packages/%40ionic/cli-utils/src/lib/project.ts#L106-L150

**Comment by dwieeb** [comment]
I know, but by getting this error:
`Error: Cannot find module '/builds/.../our-app/node_modules/@ionic/app-scripts'`

it means the CLI thought it was an Ionic Angular project, which means `type` in `ionic.config.json` was set to `ionic-angular`. My question is how it detected that or if it was set manually or leftover from a starter, etc.

**Comment by timbru31** [comment]
I've added it a while ago when we upgraded to v3 and merged our two different git repos (one for the Cordova stuff and one for the Angular app) into one.
