### ISSUE TITLE
v4: "ionic serve" doesn't log detailed errors, but "ng serve" does

### ISSUE THREAD

**Issue by sdey0081** [ionic-team/ionic-cli#3365]
**Description:**

When I run **ionic serve**, it shows and it would be difficult to find where the errors occurred, because it shows simple messages only.
```
$ ionic serve
> ng run app:serve --host=0.0.0.0 --port=8100

[INFO] Development server running!

       Local: http://localhost:8100
       External: http://198.18.6.222:8100, http://172.19.27.177:8100, http://10.0.75.1:8100, http://192.168.0.50:8100,
       http://192.168.186.1:8100, http://192.168.182.1:8100
       DevApp: ionic-starter@8100 on DESKTOP-45Q0MSR

[INFO] Browser window opened to http://localhost:8100!
```

> Failed to load resource: the server responded with a status of 404 (Not Found)  :8100/favicon.ico:1
> Failed to load resource: the server responded with a status of 404 (Not Found)  localhost/:1 

But fortunately, I can figure it out by using **ng serve**.

> i ｢wdm｣: Failed to compile.
> ERROR in src/app/app.module.ts(12,35): error TS2307: Cannot find module 'angularfire2'.
> src/app/app.module.ts(13,39): error TS2307: Cannot find module 'angularfire2/auth'.
> src/app/app.module.ts(14,40): error TS2307: Cannot find module 'angularfire2/firestore'.
> src/app/app.module.ts(15,42): error TS2307: Cannot find module 'angularfire2/storage'.
> src/app/app.module.ts(17,28): error TS2307: Cannot find module '@ionic-native/call-number/ngx'.
> src/app/app.module.ts(18,24): error TS2307: Cannot find module '@ionic-native/camera/ngx'.
> src/app/app.module.ts(19,31): error TS2307: Cannot find module '@ionic-native/email-composer/ngx'.
> src/app/app.module.ts(20,26): error TS2307: Cannot find module '@ionic-native/facebook/ngx'

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.10 (C:\Users\Admin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.9
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
```

**Other Information:**

**Comment by dwieeb** [comment]
@sdey0081 Thanks for the issue! This is fixed in the latest RC.

**Comment by jeugregg** [comment]
It still doesn't work with ionic CLI 4.1.2 ?

**Comment by dwieeb** [comment]
@jeugregg It appears to be working for me.
